version: '3.8'

services:
  mapmatcher:
    image: goncalao/map_match:latest
    build: .                      
    ports:
      - "18080:18080"
    volumes:
      - valhalla_data:/shared-data
    depends_on:
      - valhalla
    command: |
      bash -c "
        cp -r /app/data/* /shared-data/ &&
        /app/entrypoint.sh
      "

  valhalla:
    image: ghcr.io/valhalla/valhalla:latest
    ports:
      - "8002:8002"
    volumes:
      - valhalla_data:/data
    command: valhalla_service /data/valhalla.json 1

volumes:
  valhalla_data:
